config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'pages/index'
    get 'pages/no_permission'
    get 'exports/logbook/:id', to: 'exports#logbook', as: 'export_logbook'

    resources :log_standards, :bounds, :standards, :charts, :incident_types
    resources :logs, only: [:update]

    get 'locales/show', to: 'locales#show'
    get 'locales/all', to: 'locales#index'

    resources :tasks do
      collection do
        get 'defaults/:lang', to: 'tasks#defaults'
      end
    end

    resources :companies do
      resources :plants, only: %i[index new create update destroy]
    end
    resources :plants, path_prefix: '/companies/:company_id', except: %i[new create update destroy] do
      resources :sampling_lists do
        collection do
          get 'external'
          get 'internal'
        end
      end
      resources :logbooks, except: %i[new create]
      resources :inspections, :alerts, :flows, :graphs, :graph_standards
      resources :todos do
        member do
          delete 'delete_image/:image_id', to: 'todos#delete_image', as: 'delete_image'
          patch 'completed/:value', to: 'todos#completed', as: 'completed'
        end
      end
      resources :flow_reports do
        collection do
          get 'custom'
        end
      end
      resources :reports do
        collection do
          get 'latest_report'
        end
      end
      resources :supports do
        collection do
          get 'custom'
        end
      end
      resources :imports, only: %i[new create] do
        collection do
          get  'flows'
          post 'flows_create'
          get  'samplings'
          post 'samplings_create'
        end
      end
      member do
        post 'highseason'
        get 'logbook'
      end
    end

    resources :work_summaries, only: :destroy

    devise_for :users, controllers: { confirmations: 'confirmations' }, skip: :registrations
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end
    resources :users do
      collection do
        post 'uicolor'
      end
    end

    devise_scope :user do
      authenticated :user do
        root 'pages#index', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    authenticate :user, ->(u) { u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/graph.rb
# == Schema Information
#
# Table name: graphs
#
#  id                :bigint           not null, primary key
#  active            :boolean          default(TRUE)
#  comment           :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  graph_standard_id :bigint
#  report_id         :bigint
#
# Indexes
#
#  index_graphs_on_graph_standard_id  (graph_standard_id)
#  index_graphs_on_report_id          (report_id)
#
# Foreign Keys
#
#  fk_rails_...  (graph_standard_id => graph_standards.id)
#  fk_rails_...  (report_id => reports.id)

class Graph < ApplicationRecord
  belongs_to :report
  belongs_to :graph_standard
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_graph, only: [:show, :edit, :update, :destroy]

  # GET /graphs
  # GET /graphs.json
  def index
    @graphs = Graph.all
  end

  # GET /graphs/1
  # GET /graphs/1.json
  def show
  end

  # GET /graphs/new
  def new
    @graph = Graph.new
  end

  # GET /graphs/1/edit
  def edit
  end

  # POST /graphs
  # POST /graphs.json
  def create
    @graph = Graph.new(graph_params)

    respond_to do |format|
      if @graph.save
        format.html { redirect_to @graph, notice: 'Graph was successfully created.' }
        format.json { render :show, status: :created, location: @graph }
      else
        format.html { render :new }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graphs/1
  # PATCH/PUT /graphs/1.json
  def update
    respond_to do |format|
      if @graph.update(graph_params)
        format.html { redirect_to @graph, notice: 'Graph was successfully updated.' }
        format.json { render :show, status: :ok, location: @graph }
      else
        format.html { render :edit }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphs/1
  # DELETE /graphs/1.json
  def destroy
    @graph.inactive!
    respond_to do |format|
      format.html { redirect_to graphs_url, notice: 'Graph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_graph
    @graph = Graph.find(params[:id])
  end

  def graph_params
    params.require(:graph).permit(:report_id, :graph_standard_id, :active, :comment)
  end
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/views/graphs/_form.html.erb
<%= form_with(model: graph, local: true) do |form| %>
  <% if graph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(graph.errors.count, "error") %> prohibited this graph from being saved:</h2>

      <ul>
      <% graph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :report_id %>
    <%= form.text_field :report_id %>
  </div>

  <div class="field">
    <%= form.label :graph_standard_id %>
    <%= form.text_field :graph_standard_id %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit class: 'action-btn' %>
  </div>
<% end %>

app/views/graphs/edit.html.erb
<% if can? :read, Graph %>
  <%= render 'shared/buttons/option_button', alt: 'header' do %>
    <li class="option-button__option"><%= link_to t(:show, scope: :global), @graph, class: 'option-button__option-link' %></li>
  <% end %>
<% end %>

<h2 class="main__title">Editing Graph</h2>

<%= render 'form', graph: @graph %>

app/views/graphs/index.html.erb
<h1>Graphs</h1>

<table>
  <thead>
    <tr>
      <th>Report</th>
      <th>Graph standard</th>
      <th>Active</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graphs.each do |graph| %>
      <tr>
        <td><%= graph.report %></td>
        <td><%= graph.graph_standard %></td>
        <td><%= graph.active %></td>
        <td><%= graph.comment %></td>
        <td><% if can? :read, Graph %><%= link_to t(:show, scope: :global), graph %><% end %></td>
        <td><% if can? :edit, Graph %><%= link_to t(:edit, scope: :global), edit_graph_path(graph) %><% end %></td>
        <td><% if can? :destroy, Graph %><%= link_to t(:destroy, scope: :global), graph, method: :delete, data: { confirm: t(:confirm, scope: :global) } %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Graph %>
<%= link_to 'New Graph', new_plant_graph_path %>
<% end %>

app/views/graphs/new.html.erb
<h1>New Graph</h1>

<%= render 'form', graph: @graph %>

<%= link_to 'Back', graphs_path %>

app/views/graphs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Report:</strong>
  <%= @graph.report %>
</p>

<p>
  <strong>Graph standard:</strong>
  <%= @graph.graph_standard %>
</p>

<p>
  <strong>Active:</strong>
  <%= @graph.active %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @graph.comment %>
</p>

<%= link_to t(:edit, scope: :global), edit_graph_path(@graph) %> |
<%= link_to 'Back', graphs_path %>