config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'pages/index'
    get 'pages/no_permission'
    get 'exports/logbook/:id', to: 'exports#logbook', as: 'export_logbook'

    resources :log_standards, :bounds, :standards, :charts, :incident_types
    resources :logs, only: [:update]

    get 'locales/show', to: 'locales#show'
    get 'locales/all', to: 'locales#index'

    resources :tasks do
      collection do
        get 'defaults/:lang', to: 'tasks#defaults'
      end
    end

    resources :companies do
      resources :plants, only: %i[index new create update destroy]
    end
    resources :plants, path_prefix: '/companies/:company_id', except: %i[new create update destroy] do
      resources :sampling_lists do
        collection do
          get 'external'
          get 'internal'
        end
      end
      resources :logbooks, except: %i[new create]
      resources :inspections, :alerts, :flows, :graphs, :graph_standards
      resources :todos do
        member do
          delete 'delete_image/:image_id', to: 'todos#delete_image', as: 'delete_image'
          patch 'completed/:value', to: 'todos#completed', as: 'completed'
        end
      end
      resources :flow_reports do
        collection do
          get 'custom'
        end
      end
      resources :reports do
        collection do
          get 'latest_report'
        end
      end
      resources :supports do
        collection do
          get 'custom'
        end
      end
      resources :imports, only: %i[new create] do
        collection do
          get  'flows'
          post 'flows_create'
          get  'samplings'
          post 'samplings_create'
        end
      end
      member do
        post 'highseason'
        get 'logbook'
      end
    end

    resources :work_summaries, only: :destroy

    devise_for :users, controllers: { confirmations: 'confirmations' }, skip: :registrations
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end
    resources :users do
      collection do
        post 'uicolor'
      end
    end

    devise_scope :user do
      authenticated :user do
        root 'pages#index', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    authenticate :user, ->(u) { u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/views/shared/layout/_desktop_nav.html.erb
<% if @plant.persisted? %>
<nav class="desktop_nav">
  <ul class="desktop_nav__list">
    <% plant_menu = @menu[:plants] && @menu[:action] != 'logbook' ? 'desktop_nav__item--active' : '' %>
    <li class="desktop_nav__item <%= plant_menu %>"><%= link_to t(:plant, scope: [:activerecord, :models]), plant_path(plant), class: 'desktop_nav__link nav_icon nav_icon_plant' %></li>

    <% ticket_menu = @menu[:tickets] ? 'desktop_nav__item--active' : '' %>
    <li class="desktop_nav__item <%= ticket_menu %>">
      <%= link_to t(:title, scope: :ticket).pluralize, '#', class: 'desktop_nav__link nav_icon nav_icon_tickets' %>
      <div class="desktop_nav__submenu">
        <ul class="desktop_nav__subul">
          <% if can? :read, Alert %>
          <li class="desktop_nav__subli">
            <div class="desktop_nav__sublink nav_icon nav_icon_alerts"><%= t(:alert, scope: [:activerecord, :models]).pluralize %></div>
            <ul class="desktop_nav__subul">
              <% active = @menu[:alerts] && @menu[:action] %>
              <li class="desktop_nav__subli <%= active == 'index' && 'desktop_nav__subli--active' %>"><%= link_to t(:history, scope: :alert), plant_alerts_path(@plant), class: 'desktop_nav__sublink' %></li>
              <% if can? :create, Alert %>
              <li class="desktop_nav__subli <%= active == 'new' && 'desktop_nav__subli--active' %>"><%= link_to t(:new, scope: :alert), new_plant_alert_path(@plant), class: 'desktop_nav__sublink' %></li>
              <% end %>
            </ul>
          </li>
          <% end %>

          <% if can? :read, Support %>
          <li class="desktop_nav__subli">
            <div class="desktop_nav__sublink nav_icon nav_icon_supports"><%= t(:support, scope: [:activerecord, :models]).pluralize %></div>
            <ul class="desktop_nav__subul">
              <% active = @menu[:supports] && @menu[:action] %>
              <li class="desktop_nav__subli <%= active == 'index' && 'desktop_nav__subli--active' %>"><%= link_to t(:history, scope: :support), plant_supports_path(@plant), class: 'desktop_nav__sublink' %></li>
              <% if can? :create, Support %>
              <li class="desktop_nav__subli <%= active == 'new' && 'desktop_nav__subli--active' %>"><%= link_to t(:new, scope: :support), new_plant_support_path(@plant), class: 'desktop_nav__sublink' %></li>
              <% end %>
            </ul>
          </li>
          <% end %>

          <% if can? :read, Inspection %>
          <li class="desktop_nav__subli">
            <div class="desktop_nav__sublink nav_icon nav_icon_inspections"><%= t(:plural, scope: :inspection) %></div>
            <ul class="desktop_nav__subul">
              <% active = @menu[:inspections] && @menu[:action] %>
              <li class="desktop_nav__subli <%= active == 'index' && 'desktop_nav__subli--active' %>"><%= link_to t(:history, scope: :inspection), plant_inspections_path(@plant), class: 'desktop_nav__sublink' %></li>
              <% if can? :create, Inspection %>
              <li class="desktop_nav__subli <%= active == 'new' && 'desktop_nav__subli--active' %>"><%= link_to t(:new, scope: :inspection), new_plant_inspection_path(@plant), class: 'desktop_nav__sublink' %></li>
              <% end %>
            </ul>
          </li>
          <% end %>
          <div class="unclick--desktop_menu"></div>
        </ul>
      </div>
    </li>

    <% if can? :read, Logbook %>
    <% logbook_menu = @menu[:logbooks] || (@menu[:plants] && @menu[:action] == 'logbook') ? 'desktop_nav__item--active' : '' %>
    <li class="desktop_nav__item <%= logbook_menu %>">
      <%= link_to t(:logbook, scope: [:activerecord, :models]).pluralize, '#', class: 'desktop_nav__link nav_icon nav_icon_logbooks' %>
      <div class="desktop_nav__submenu">
        <ul class="desktop_nav__subul">
          <% active = @menu[:plants] && @menu[:action] == 'logbook' %>
          <li class="desktop_nav__subli <%= active && 'desktop_nav__subli--active' %>"><%= link_to t(:title, scope: :logbook), logbook_plant_path(plant), class: 'desktop_nav__sublink' %></li>
          <% active = @menu[:logbooks] && @menu[:action] %>
          <li class="desktop_nav__subli <%= active == 'index' && 'desktop_nav__subli--active' %>"><%= link_to t(:history, scope: :logbook), plant_logbooks_path(plant), class: 'desktop_nav__sublink' %></li>
          <div class="unclick--desktop_menu"></div>
        </ul>
      </div>
    </li>
    <% end %>

    <% if can? :read, Todo %>
    <% todo_menu = @menu[:todos] ? 'desktop_nav__item--active' : '' %>
    <li class="desktop_nav__item <%= todo_menu %>">
      <%= link_to t(:todo, scope: [:activerecord, :models]).pluralize, '#', class: 'desktop_nav__link nav_icon nav_icon_todos' %>
      <div class="desktop_nav__submenu">
        <ul class="desktop_nav__subul">
          <% active = @menu[:todos] && @menu[:action] %>
          <li class="desktop_nav__subli <%= active == 'index' ? 'desktop_nav__subli--active' : '' %>"><%= link_to t(:history, scope: :todo), plant_todos_path(plant), class: 'desktop_nav__sublink' %></li>
          <li class="desktop_nav__subli <%= active == 'new' ? 'desktop_nav__subli--active' : '' %>"><%= link_to t(:new, scope: :todo), new_plant_todo_path(plant), class: 'desktop_nav__sublink' %></li>
          <div class="unclick--desktop_menu"></div>
        </ul>
      </div>
    </li>
    <% end %>

  </ul>
</nav>
<% end %>

app/views/shared/layout/_mobile_nav.html.erb
<nav class="mobile_nav">
  <ul class="mobile_nav__list">
    <% if can? :read, Company %>
    <% companies_menu = @menu[:companies] ? 'mobile_nav__item--active' : '' %>
    <li class="mobile_nav__item <%= companies_menu %>">
      <%= link_to t(:companies, scope: [:header, :menu]), companies_path, class: 'mobile_nav__link' %>
    </li>
    <% end %>

    <% if @user_plants %>
    <li class="mobile_nav__item">
      <a class="mobile_nav__link" href="#"><%= t(:plants, scope: [:header, :menu]) %></a>
      <ul class="mobile_nav__submenu-list">
        <% @user_plants.each do |plant| %>
        <li class="mobile_nav__subitem"><%= link_to plant.name, plant_path(plant), class: 'mobile_nav__sublink' %></li>
        <% end %>
      </ul>
    </li>
    <% end %>

    <% if @plant.present? && @plant.persisted? %>
    <% if can? :read, Plant %>
    <% plant_menu = @menu[:plants] ? 'mobile_nav__item--active' : '' %>
    <li class="mobile_nav__item mobile_nav__item--active">
      <a class="mobile_nav__link" href="#"><%= @plant.name %></a>
      <ul class="mobile_nav__submenu-list">
        <li class="mobile_nav__subitem">
          <%= link_to t(:plant, scope: [:activerecord, :models]).downcase, plant_path(@plant), class: 'mobile_nav__sublink' %>
        </li>
        <% ticket_menu = @menu[:tickets] ? 'mobile_nav__subitem--active' : '' %>
        <li class="mobile_nav__subitem <%= ticket_menu %>">
          <a href="#" class="mobile_nav__sublink"><%= t(:title, scope: :ticket).pluralize.downcase %></a>
          <ul class="mobile_nav__submenu-list">

            <% if can? :read, Alert %>
            <% active = @menu[:alerts] ? 'mobile_nav__sublink--active' : '' %>
            <li class="mobile_nav__subitem <%= active %>"><a href="#" class="mobile_nav__sublink"><%= t(:alert, scope: [:activerecord, :models]).pluralize.downcase %></a>
              <ul class="mobile_nav__submenu-list">
                <% active = @menu[:alerts] && @menu[:action] %>
                <li class="mobile_nav__subitem <%= active == 'index' && 'mobile_nav__subitem--active' %>"><%= link_to t(:history, scope: :alert).downcase, plant_alerts_path(@plant), class: 'mobile_nav__sublink' %></li>
                <% if can? :create, Alert %>
                <li class="mobile_nav__subitem <%= active == 'new' && 'mobile_nav__subitem--active' %>"><%= link_to t(:new, scope: :alert).downcase, new_plant_alert_path(@plant), class: 'mobile_nav__sublink' %></li>
                <% end %>
              </ul>
            </li>
            <% end %>

            <% if can? :read, Support %>
            <% active = @menu[:supports] ? 'mobile_nav__subitem--active' : '' %>
            <li class="mobile_nav__subitem <%= active %>"><a href="#" class="mobile_nav__sublink"><%= t(:support, scope: [:activerecord, :models]).pluralize.downcase %></a>
              <ul class="mobile_nav__submenu-list">
                <% active = @menu[:supports] && @menu[:action] %>
                <li class="mobile_nav__subitem <%= active == 'index' && 'mobile_nav__subitem--active' %>"><%= link_to t(:history, scope: :support).downcase, plant_supports_path(@plant), class: 'mobile_nav__sublink' %></li>
                <% if can? :create, Support %>
                <li class="mobile_nav__subitem <%= active == 'new' && 'mobile_nav__subitem--active' %>"><%= link_to t(:new, scope: :support).downcase, new_plant_support_path(@plant), class: 'mobile_nav__sublink' %></li>
                <% end %>
              </ul>
            </li>
            <% end %>

            <% if can? :read, Inspection %>
            <% active = @menu[:inspections] ? 'mobile_nav__subitem--active' : '' %>
            <li class="mobile_nav__subitem"><a href="#" class="mobile_nav__sublink"><%= t(:plural, scope: :inspection).downcase %></a>
              <ul class="mobile_nav__submenu-list">
                <% active = @menu[:inspections] && @menu[:action] %>
                <li class="mobile_nav__subitem <%= active == 'index' && 'mobile_nav__subitem--active' %>"><%= link_to t(:history, scope: :inspection).downcase, plant_inspections_path(@plant), class: 'mobile_nav__sublink' %></li>
                <% if can? :create, Inspection %>
                <li class="mobile_nav__subitem <%= active == 'new' && 'mobile_nav__subitem--active' %>"><%= link_to t(:new, scope: :inspection).downcase, new_plant_inspection_path(@plant), class: 'mobile_nav__sublink' %></li>
                <% end %>
              </ul>
            </li>
            <% end %>
          </ul>
        </li>

        <% if can? :read, Logbook %>
        <% logbooks_menu = @menu[:logbooks] || (@menu[:plants] && @menu[:action] == 'logbook') ? 'mobile_nav__subitem--active' : '' %>
        <li class="mobile_nav__subitem <%= logbooks_menu %>">
          <a href="#" class="mobile_nav__sublink"><%= t(:logbook, scope: [:activerecord, :models]).pluralize.downcase %></a>
          <ul class="mobile_nav__submenu-list">
            <% active = @menu[:plants] && @menu[:action] == 'logbook' %>
            <li class="mobile_nav__subitem <%= active && 'mobile_nav__subitem--active' %>"><%= link_to t(:logbook, scope: [:activerecord, :models]).downcase, logbook_plant_path(@plant), class: 'mobile_nav__sublink' %></li>
            <% active = @menu[:logbooks] && @menu[:action] %>
            <li class="mobile_nav__subitem <%= active == 'index' && 'mobile_nav__subitem--active' %>"><%= link_to t(:history, scope: :logbook).downcase, plant_logbooks_path(@plant), class: 'mobile_nav__sublink' %></li>
          </ul>
        </li>
        <% end %>

        <% if can? :read, Todo %>
        <% todos_menu = @menu[:todos] ? 'mobile_nav__subitem--active' : '' %>
        <li class="mobile_nav__subitem <%= todos_menu %>">
          <a href="#" class="mobile_nav__sublink"><%= t(:todo, scope: [:activerecord, :models]).pluralize %></a>
          <ul class="mobile_nav__submenu-list">
            <% active = @menu[:todos] && @menu[:action] %>
            <li class="mobile_nav__subitem <%= active == 'index' && 'mobile_nav__subitem--active' %>"><%= link_to t(:history, scope: :todo), plant_todos_path(@plant), class: 'mobile_nav__sublink' %></li>
            <li class="mobile_nav__subitem <%= active == 'new' && 'mobile_nav__subitem--active' %>"><%= link_to t(:new, scope: :todo), new_plant_todo_path(@plant), class: 'mobile_nav__sublink' %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </li>
    <% end %>
    <% end %>

    <% if can? :read, User && (current_user.admin? || current_user.operations_manager? ) %>
    <% users_menu = @menu[:users] ? 'mobile_nav__item--active' : '' %>
    <li class="mobile_nav__item <%= users_menu %>">
      <%= link_to t(:users, scope: [:header, :menu]), users_path, class: 'mobile_nav__link' %>
      <ul class="mobile_nav__submenu-list">
        <li class="mobile_nav__subitem"><%= link_to 'all users', users_path, class: 'mobile_nav__sublink' %></li>
        <% if can? :create, User %>
        <li class="mobile_nav__subitem"><%= link_to 'new user', new_user_path, class: 'mobile_nav__sublink' %></li>
        <% end %>
      </ul>
    </li>
    <% end %>
  </ul>
</nav>

app/views/shared/layout/_notifications.html.erb
<div class="toast__container">
  <div class="toast__cell">
    <% if notice %>
    <%= render 'shared/notifications/notification', color: 'blue', type: 'Notice', text: notice %>
    <% end %>

    <% if alert %>
    <%= render 'shared/notifications/notification', color: 'red', type: 'Alert', text: alert %>
    <% end %>
  </div>
</div>

app/views/shared/layout/_user_options.html.erb
<nav class="user_options">
  <ul class="user_options__list">
    <li class="user_options__item--ui">
      <a class="user_options__link--<%= current_user.interface_color %>-ui" href="#">
        <% if current_user.dark? %>
        <svg class="user_options__svg user_options__sun"><use xlink:href="#sun"></use><svg>
        <% else %>
        <svg class="user_options__svg user_options__moon"><use xlink:href="#moon"></use><svg>
        <% end %>
      </a>
    </li>
    <li class="user_options__item">
      <a class="user_options__link--users" href="#">
        <svg class="user_options__svg user_options__user"><use xlink:href="#user"></use><svg>
      </a>
      <div class="options_menu">
        <ul class="options_menu__list">
          <li class="options_menu__item"><div class="options_menu__link"><%= t(:hi, scope: :global, name: current_user.name) %></div></li>
          <li class="options_menu__item"><%= link_to t(:edit_profile, scope: :global), edit_user_path(current_user.id), class: 'options_menu__link' %></li>
          <li class="options_menu__item"><%= link_to t(:change_password, scope: :global), edit_user_registration_path, class: 'options_menu__link' %></li>
          <li class="options_menu__separator"></li>
          <li class="options_menu__item"><%= link_to t(:logout, scope: :global), destroy_user_session_path, method: :delete, class: 'options_menu__link'  %></li>
        </ul>
        <div class="unclick--user"></div>
      </div>
    </li>
  </ul>
</nav>