config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'pages/index'
    get 'pages/no_permission'
    get 'exports/logbook/:id', to: 'exports#logbook', as: 'export_logbook'

    resources :log_standards, :bounds, :standards, :charts, :incident_types
    resources :logs, only: [:update]

    get 'locales/show', to: 'locales#show'
    get 'locales/all', to: 'locales#index'

    resources :tasks do
      collection do
        get 'defaults/:lang', to: 'tasks#defaults'
      end
    end

    resources :companies do
      resources :plants, only: %i[index new create update destroy]
    end
    resources :plants, path_prefix: '/companies/:company_id', except: %i[new create update destroy] do
      resources :sampling_lists do
        collection do
          get 'external'
          get 'internal'
        end
      end
      resources :logbooks, except: %i[new create]
      resources :inspections, :alerts, :flows, :graphs, :graph_standards
      resources :todos do
        member do
          delete 'delete_image/:image_id', to: 'todos#delete_image', as: 'delete_image'
          patch 'completed/:value', to: 'todos#completed', as: 'completed'
        end
      end
      resources :flow_reports do
        collection do
          get 'custom'
        end
      end
      resources :reports do
        collection do
          get 'latest_report'
        end
      end
      resources :supports do
        collection do
          get 'custom'
        end
      end
      resources :imports, only: %i[new create] do
        collection do
          get  'flows'
          post 'flows_create'
          get  'samplings'
          post 'samplings_create'
        end
      end
      member do
        post 'highseason'
        get 'logbook'
      end
    end

    resources :work_summaries, only: :destroy

    devise_for :users, controllers: { confirmations: 'confirmations' }, skip: :registrations
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end
    resources :users do
      collection do
        post 'uicolor'
      end
    end

    devise_scope :user do
      authenticated :user do
        root 'pages#index', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    authenticate :user, ->(u) { u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id            :bigint           not null, primary key
#  active        :boolean          default(TRUE)
#  name          :string
#  taxid         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  bf_contact_id :bigint
#  contact_id    :bigint
#  industry_id   :bigint
#
# Indexes
#
#  index_companies_on_bf_contact_id  (bf_contact_id)
#  index_companies_on_contact_id     (contact_id)
#  index_companies_on_industry_id    (industry_id)
#
# Foreign Keys
#
#  fk_rails_...  (industry_id => industries.id)

class Company < ApplicationRecord
  has_many :plants, dependent: :destroy
  belongs_to :industry

  belongs_to :contact, class_name: 'User'
  belongs_to :bf_contact, class_name: 'User'

  validates :name, presence: true, uniqueness: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_industries, only: [:new, :edit, :show, :create]
  before_action :set_users, only: [:new, :create, :edit, :update]
  load_and_authorize_resource

  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.admin? ? Company.includes(:industry).active : current_user.plants.includes(company: [:industry]).map(&:company)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @plants = @company.plants.active
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to new_company_plant_path(@company), notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.inactive!
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_industries
    @industries = Industry.all_names
  end

  def set_users
    @users = User.filtered.active.sort_by_id
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:active, :name, :taxid, :industry_id, :contact_id, :bf_contact_id)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: t(:name, scope: [:activerecord, :attributes, :company]) %>
  </div>

  <div class="field">
    <%= form.label :taxid %>
    <%= form.text_field :taxid, placeholder: t(:taxid, scope: [:activerecord, :attributes, :company]) %>
  </div>

  <div class="field no-border">
    <%= form.label :industry_id %>
    <%= form.collection_select(:industry_id, @industries, :first, :second, {prompt: t(:select_industry, scope: :company)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :contact_id %>
    <%= form.collection_select(:contact_id, @users, :id, :full_name, {prompt: t(:select_a_contact, scope: :company)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :bf_contact_id %>
    <%= form.collection_select(:bf_contact_id, @users, :id, :full_name, {prompt: t(:select_a_contact, scope: :company)})  %>
  </div>

  <div class="actions">
    <%= form.submit class: 'action-btn' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% if can? :read, Company %>
  <%= render 'shared/buttons/option_button', alt: 'header' do %>
    <li class="option-button__option"><%= link_to t(:show, scope: :global).downcase, @company, class: 'option-button__option-link' %></li>
  <% end %>
<% end %>

<h2 class="main__title"><%= t(:edit, scope: :company) %></h2>

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<% if can? :create, Company %>
  <%= render 'shared/buttons/option_button', alt: 'header' do %>
    <li class="option-button__option"><%= link_to t(:new, scope: :company).downcase, new_company_path, class: 'option-button__option-link' %></li>
  <% end %>
<% end %>

<h2 class="main__title"><%= t(:index, scope: :company) %></h2>

<%= render 'shared/tables/elements_list', headers: [t(:name, scope: [:activerecord, :attributes, :company]).camelize, t(:taxid, scope: [:activerecord, :attributes, :company]).camelize, t(:industry, scope: [:activerecord, :attributes, :company]).camelize, t(:options, scope: :global).camelize], title: t(:your_companies, scope: :company) do %>
<% @companies.each do |company| %>
<tr class="table_main__table-row">
  <td class="table_main__table-data--left-text"><%= link_to company.name, company, class: 'table_main__link-show' %></td>
  <td class="table_main__table-data"><%= company.taxid %></td>
  <td class="table_main__table-data"><%= t(company.industry.name.parameterize(separator: '_'), scope: [:activerecord, :attributes, :industry, :industries]) %></td>
  <td class="table_main__table-data--options">
    <a href="#" class="table_main__link--options"></a>
    <div class="options_menu">
      <ul class="options_menu__list">
        <% if can? :read, Company %><li class="options_menu__item"><%= link_to t(:show, scope: :global).downcase, company, class: 'options_menu__link' %></li><% end %>
        <% if can? :edit, Company %><li class="options_menu__item"><%= link_to t(:edit, scope: :global).downcase, edit_company_path(company), class: 'options_menu__link' %></li><% end %>
        <% if can? :destroy, Company %><li class="options_menu__item"><%= link_to t(:destroy, scope: :global).downcase, company, method: :delete, data: { confirm: t(:confirm, scope: :global) }, class: 'options_menu__link' %></li><% end %>
        <% if can? :create, Plant %>
        <li class="options_menu__separator"></li>
        <li class="options_menu__item"><%= link_to t(:new_plant, scope: :plant).downcase, new_company_plant_path(company), class: 'options_menu__link' %></li>
        <% end %>
      </ul>
      <div class="unclick"></div>
    </div>
  </td>
</tr>
<% end %>
<% end %>

app/views/companies/new.html.erb
<h2 class="main__title"><%= t(:new, scope: :company) %></h2>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<% if can? :edit, Company %>
  <%= render 'shared/buttons/option_button', alt: 'header' do %>
    <li class="option-button__option"><%= link_to t(:edit, scope: :global).downcase, edit_company_path(@company), class: 'option-button__option-link' %></li>
    <% if can? :create, Plant %>
    <li class="option-button__separator"></li>
    <li class="option-button__option"><%= link_to t(:new, scope: :plant, name: :title ).downcase, new_company_plant_path(@company), class: 'option-button__option-link', data: { turbolinks: false } %></li>
    <% end %>
  <% end %>
<% end %>

<h2 class="main__title"><%= @company.name %></h2>

<div class="view_info">
  <p class="view_info__data"><%= @company.name %></p>
  <p class="view_info__title"><%= t(:name, scope: [:activerecord, :attributes, :company]) %></p>
</div>

<div class="view_info">
  <p class="view_info__data"><%= @company.taxid %></p>
  <p class="view_info__title"><%= t(:taxid, scope: [:activerecord, :attributes, :company]) %></p>
</div>

<div class="view_info">
  <p class="view_info__data"><%= @company.industry.name %></p>
  <p class="view_info__title"><%= t(:industry_id, scope: [:activerecord, :attributes, :company]) %></p>
</div>

<div class="view_info">
  <p class="view_info__data"><%= @company.contact&.full_name  %></p>
  <p class="view_info__title"><%= t(:contact_id, scope: [:activerecord, :attributes, :company]) %></p>
</div>

<div class="view_info">
  <p class="view_info__data"><%= @company.bf_contact&.full_name  %></p>
  <p class="view_info__title"><%= t(:bf_contact_id, scope: [:activerecord, :attributes, :company]) %></p>
</div>

<div class="space"></div>

<%= render 'shared/tables/elements_list', headers: [t(:title_plural, scope: :plant), t(:options, scope: :global)], title: t(:related_plants, scope: [:plant]) do %>
<% @plants.each do |plant| %>
<tr class="table_main__table-row">
  <td class="table_main__table-data--left-text"><%= link_to plant.name, plant, class: 'table_main__link-show' %></td>
  <td class="table_main__table-data--options">
    <a href="#" class="table_main__link--options"></a>
    <div class="options_menu">
      <ul class="options_menu__list">
        <% if can? :read, Plant %><li class="options_menu__item"><%= link_to t(:show, scope: :global), plant, class: 'options_menu__link' %></li><% end %>
        <% if can? :edit, Plant %><li class="options_menu__item"><%= link_to t(:edit, scope: :global), edit_plant_path(plant), class: 'options_menu__link', data: { turbolinks: false } %></li><% end %>
        <% if can? :destroy, Plant %><li class="options_menu__item"><%= link_to t(:destroy, scope: :global), plant, class: 'options_menu__link', method: :delete, data: { confirm: t(:confirm, scope: :global) } %></li><% end %>
      </ul>
      <div class="unclick"></div>
    </div>
  </td>
</tr>
<% end %>
<% end %>