config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'pages/index'
    get 'pages/no_permission'
    get 'exports/logbook/:id', to: 'exports#logbook', as: 'export_logbook'

    resources :log_standards, :bounds, :standards, :charts, :incident_types
    resources :logs, only: [:update]

    get 'locales/show', to: 'locales#show'
    get 'locales/all', to: 'locales#index'

    resources :tasks do
      collection do
        get 'defaults/:lang', to: 'tasks#defaults'
      end
    end

    resources :companies do
      resources :plants, only: %i[index new create update destroy]
    end
    resources :plants, path_prefix: '/companies/:company_id', except: %i[new create update destroy] do
      resources :sampling_lists do
        collection do
          get 'external'
          get 'internal'
        end
      end
      resources :logbooks, except: %i[new create]
      resources :inspections, :alerts, :flows, :graphs, :graph_standards
      resources :todos do
        member do
          delete 'delete_image/:image_id', to: 'todos#delete_image', as: 'delete_image'
          patch 'completed/:value', to: 'todos#completed', as: 'completed'
        end
      end
      resources :flow_reports do
        collection do
          get 'custom'
        end
      end
      resources :reports do
        collection do
          get 'latest_report'
        end
      end
      resources :supports do
        collection do
          get 'custom'
        end
      end
      resources :imports, only: %i[new create] do
        collection do
          get  'flows'
          post 'flows_create'
          get  'samplings'
          post 'samplings_create'
        end
      end
      member do
        post 'highseason'
        get 'logbook'
      end
    end

    resources :work_summaries, only: :destroy

    devise_for :users, controllers: { confirmations: 'confirmations' }, skip: :registrations
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end
    resources :users do
      collection do
        post 'uicolor'
      end
    end

    devise_scope :user do
      authenticated :user do
        root 'pages#index', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    authenticate :user, ->(u) { u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/inspection.rb
# == Schema Information
#
# Table name: inspections
#
#  id                         :bigint           not null, primary key
#  active                     :boolean          default(TRUE)
#  bida_comments              :text
#  birds                      :boolean
#  date                       :date
#  on_site_client             :boolean
#  plant_odor_description     :text
#  pumps_comments             :text
#  pumps_noise_description    :text
#  pumps_psi                  :float
#  screen_comments            :text
#  summary_comments           :text
#  worms_activity_description :text
#  worms_color_description    :text
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  bed_compaction_id          :bigint
#  collection_bin_id          :bigint
#  fly_id                     :bigint
#  noise_id                   :bigint
#  odor_id                    :bigint
#  on_site_user_id            :bigint
#  piping_id                  :bigint
#  plant_id                   :bigint
#  ponding_id                 :bigint
#  report_technician_id       :bigint
#  screen_id                  :bigint
#  sprinklers_head_id         :bigint
#  sprinklers_pressure_id     :bigint
#  system_surface_id          :bigint
#  user_id                    :bigint
#  worms_activity_id          :bigint
#  worms_color_id             :bigint
#  worms_density_id           :bigint
#
# Indexes
#
#  index_inspections_on_bed_compaction_id       (bed_compaction_id)
#  index_inspections_on_collection_bin_id       (collection_bin_id)
#  index_inspections_on_fly_id                  (fly_id)
#  index_inspections_on_noise_id                (noise_id)
#  index_inspections_on_odor_id                 (odor_id)
#  index_inspections_on_on_site_user_id         (on_site_user_id)
#  index_inspections_on_piping_id               (piping_id)
#  index_inspections_on_plant_id                (plant_id)
#  index_inspections_on_ponding_id              (ponding_id)
#  index_inspections_on_report_technician_id    (report_technician_id)
#  index_inspections_on_screen_id               (screen_id)
#  index_inspections_on_sprinklers_head_id      (sprinklers_head_id)
#  index_inspections_on_sprinklers_pressure_id  (sprinklers_pressure_id)
#  index_inspections_on_system_surface_id       (system_surface_id)
#  index_inspections_on_user_id                 (user_id)
#  index_inspections_on_worms_activity_id       (worms_activity_id)
#  index_inspections_on_worms_color_id          (worms_color_id)
#  index_inspections_on_worms_density_id        (worms_density_id)
#
# Foreign Keys
#
#  fk_rails_...  (bed_compaction_id => bed_compactions.id)
#  fk_rails_...  (collection_bin_id => collection_bins.id)
#  fk_rails_...  (fly_id => flies.id)
#  fk_rails_...  (noise_id => noises.id)
#  fk_rails_...  (odor_id => odors.id)
#  fk_rails_...  (piping_id => pipings.id)
#  fk_rails_...  (plant_id => plants.id)
#  fk_rails_...  (ponding_id => pondings.id)
#  fk_rails_...  (screen_id => screens.id)
#  fk_rails_...  (sprinklers_head_id => sprinklers_heads.id)
#  fk_rails_...  (sprinklers_pressure_id => sprinklers_pressures.id)
#  fk_rails_...  (system_surface_id => system_surfaces.id)
#  fk_rails_...  (user_id => users.id)
#  fk_rails_...  (worms_activity_id => worms_activities.id)
#  fk_rails_...  (worms_color_id => worms_colors.id)
#  fk_rails_...  (worms_density_id => worms_densities.id)

class Inspection < ApplicationRecord
  belongs_to :user
  belongs_to :plant
  belongs_to :screen
  belongs_to :collection_bin
  belongs_to :noise
  belongs_to :sprinklers_pressure
  belongs_to :sprinklers_head
  belongs_to :piping
  belongs_to :system_surface
  belongs_to :bed_compaction
  belongs_to :ponding
  belongs_to :odor
  belongs_to :fly

  has_many :fluents

  has_and_belongs_to_many :users
  belongs_to :on_site_user, class_name: 'User'
  belongs_to :report_technician, class_name: 'User'

  accepts_nested_attributes_for :fluents, allow_destroy: true

  def send_notifications!
    users = user_ids.map { |i| User.find(i) }
    users.each do |user|
      NotificationMailer.inspection_notification(user, self).deliver_later
    end
  end

  def title
    "##{id} #{date}"
  end
end

app/models/plant.rb
# == Schema Information
#
# Table name: plants
#
#  id                             :bigint           not null, primary key
#  active                         :boolean          default(TRUE)
#  address01                      :string
#  address02                      :string
#  code                           :string
#  flow_design                    :integer
#  high_season                    :jsonb
#  name                           :string
#  phone                          :string
#  report_preface                 :string
#  startup_date                   :date
#  state                          :string
#  system_purpose                 :string
#  system_size                    :string
#  unit_number                    :string
#  zip                            :string
#  created_at                     :datetime         not null
#  updated_at                     :datetime         not null
#  bf_contact_id                  :bigint
#  company_id                     :bigint           not null
#  contact_id                     :bigint
#  country_id                     :bigint
#  discharge_point_id             :bigint
#  logbook_bf_responsible_id      :bigint
#  logbook_bf_supervisor_id       :bigint
#  logbook_company_responsible_id :bigint
#
# Indexes
#
#  index_plants_on_bf_contact_id                   (bf_contact_id)
#  index_plants_on_company_id                      (company_id)
#  index_plants_on_contact_id                      (contact_id)
#  index_plants_on_country_id                      (country_id)
#  index_plants_on_discharge_point_id              (discharge_point_id)
#  index_plants_on_logbook_bf_responsible_id       (logbook_bf_responsible_id)
#  index_plants_on_logbook_bf_supervisor_id        (logbook_bf_supervisor_id)
#  index_plants_on_logbook_company_responsible_id  (logbook_company_responsible_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#  fk_rails_...  (country_id => countries.id)
#  fk_rails_...  (discharge_point_id => discharge_points.id)

class Plant < ApplicationRecord
  after_create_commit :generate_logbook
  before_save :filter_unit_number

  # validations
  validates :code, presence: true, uniqueness: true
  validates :flow_design, numericality: { greater_than: 0 }

  belongs_to :company
  belongs_to :country
  belongs_to :discharge_point
  has_and_belongs_to_many :users

  has_many :alerts, dependent: :destroy
  has_many :supports, dependent: :destroy
  has_many :inspections, dependent: :destroy
  has_many :todos

  has_many :task_lists
  has_many :logbooks

  has_many :flows, dependent: :destroy
  has_many :flow_reports, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :graph_standards, dependent: :destroy

  belongs_to :logbook_bf_responsible, class_name: 'User'
  belongs_to :logbook_bf_supervisor, class_name: 'User'
  belongs_to :logbook_company_responsible, class_name: 'User'

  belongs_to :contact, class_name: 'User'
  belongs_to :bf_contact, class_name: 'User'

  has_many :standards, dependent: :destroy
  has_many :sampling_lists, dependent: :destroy

  has_one_attached :cover
  has_one_attached :discharge_permit

  accepts_nested_attributes_for :standards, allow_destroy: true
  accepts_nested_attributes_for :sampling_lists, allow_destroy: true
  accepts_nested_attributes_for :task_lists, allow_destroy: false
  accepts_nested_attributes_for :logbooks, allow_destroy: false
  accepts_nested_attributes_for :graph_standards, allow_destroy: true

  serialize :unit_number, Array

  enum frecuency: %w[daily weekly every_2_weeks monthly every_x_months]

  scope :filter_by_id, ->(id) { where.not(id: id) }

  def generate_logbook
    logbooks.create(task_list: task_lists.last)
  end

  def filter_unit_number
    self.unit_number = unit_number.reject(&:empty?)
  end

  def metrics
    country.metric
  end

  def cover_hero
    cover.variant(resize: '2280')
  end

  def in_high_season?
    return false if high_season['in'].blank? && high_season['out'].blank?

    current_date = Date.today
    begin
      in_date = Date.parse(high_season['in'])
      out_date = Date.parse(high_season['out'])
    rescue ArgumentError
      flash.now[:alert] = 'Fechas no válidas'
    end

    in_date < current_date && out_date > current_date
  end

  def without_seasons?(date)
    season = check_season(date)
    season == :no_season
  end

  def between_high_season?(date)
    season = check_season(date)
    (season != :out_season || season != :no_valid_dates)
  end

  def between_low_season?(date)
    season = check_season(date)
    (season != :in_season || season != :no_valid_dates)
  end

  def check_season(date = Date.today)
    return :no_season if high_season['in'].blank? && high_season['out'].blank?

    current_date = current_year_date_from_string(date)
    begin
      in_date = current_year_date_from_string(high_season['in'])
      out_date = current_year_date_from_string(high_season['out'])
    rescue ArgumentError
      return :no_valid_dates
    end

    in_date <= current_date && current_date <= out_date ? :in_season : :out_season
  end

  def current_year_date_from_string(str)
    current_year = Date.today.year
    data = str.split('-')

    Date.parse("#{current_year}-#{data.second}-#{data.third}")
  end
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :set_create_assignment, only: :create
  before_action :generate_users, only: [:new, :create, :edit, :update]
  prepend_before_action :set_variables, only: %i[new create edit update]
  load_and_authorize_resource

  # GET /inspections
  # GET /inspections.json
  def index
    @plant = Plant.find(params[:plant_id])
    @inspections = @plant.inspections.active.order('id DESC')
  end

  # GET /inspections/1
  # GET /inspections/1.json
  def show
    @plant = Plant.find(params[:plant_id])
    @inspection = @plant.inspections.find(params[:id])
    @fluents = @inspection.fluents.includes(:output, :color, :odor).order(:output_id)
  rescue ActiveRecord::RecordNotFound => _e
    redirect_to pages_no_permission_path, notice: t(:access_not_allowed, scope: :global)
  end

  # GET /inspections/new
  def new
    @inspection = Inspection.new
    @plant = Plant.find(params[:plant_id])

    outputs = Output.all
    outputs.each do |output|
      @inspection.fluents.build(output: output)
    end
  end

  # GET /inspections/1/edit
  def edit
    @plant = Plant.find(params[:plant_id])
    @inspection = @plant.inspections.find(params[:id])
    @fluents = @inspection.fluents.includes(:output)
  rescue ActiveRecord::RecordNotFound => _e
    redirect_to pages_no_permission_path, notice: t(:access_not_allowed, scope: :global)
  end

  # POST /inspections
  # POST /inspections.json
  def create
    respond_to do |format|
      if @inspection.save
        @inspection.send_notifications!
        format.html { redirect_to plant_inspections_path(@plant), notice: t(:successfully_created, scope: :inspection) }
        format.json { render :show, status: :created, location: @inspection }
      else
        format.html { render :new }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to plant_inspections_path(@plant), notice: t(:successfully_updated, scope: :inspection) }
        format.json { render :show, status: :ok, location: @inspection }
      else
        format.html { render :edit }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    @inspection.inactive!
    respond_to do |format|
      format.html { redirect_to plant_inspections_path(@plant), notice: t(:successfully_deleted, scope: :inspection) }
      format.json { head :no_content }
    end
  end

  private

  def set_create_assignment
    @inspection = Inspection.new(inspection_params)
    @inspection.user = current_user
    @inspection.plant = Plant.find(params[:plant_id])
  end

  def set_variables
    @plant = Plant.find(params[:plant_id])
    @screens = Screen.all_options
    @collectionbins = CollectionBin.all_options
    @noises = Noise.all_options
    @sprinklers_pressures = SprinklersPressure.all_options
    @sprinklers_heads = SprinklersHead.all_options
    @pipings = Piping.all_options
    @system_surfaces = SystemSurface.all_options
    @bed_compactions = BedCompaction.all_options
    @pondings = Ponding.all_options
    @flies = Fly.all_options
    @birds = [[I18n.t(:_yes, scope: :global), true], [I18n.t(:_no, scope: :global), false]]
    @on_site_client = [[I18n.t(:_yes, scope: :global) + ' (Describe)', true], [I18n.t(:_no, scope: :global), false]]
    @worms_color = WormsColor.all_options
    @worms_activity = WormsActivity.all_options
    @worms_density = WormsDensity.all_options
    @colors = Color.all_options
    @odors = Odor.all_options
  end

  def generate_users
    @users = User.filtered_by(@plant).sort
    @company_users = User.filtered_by(@plant).from_company.sort
    @biofiltro_users = User.filtered_by(@plant).from_biofiltro.sort
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # :inspection_id, :worms_color_id, :color_description, :worms_activity_id, :activity_description, :worms_density_id
  def inspection_params
    params.require(:inspection).permit(:active, :date, :user_id, :plant_id, :on_site_client, :on_site_user_id, :report_technician_id,
      :screen_id, :collection_bin_id, :screen_comments, :noise_id, :pumps_noise_description, :pumps_psi, :sprinklers_pressure_id,
      :sprinklers_head_id, :piping_id, :pumps_comments, :system_surface_id, :bed_compaction_id, :ponding_id, :bida_comments,:odor_id,
      :plant_odor_description, :birds, :fly_id, :summary_comments, :worms_color_id, :worms_color_description, :worms_activity_id,
      :worms_activity_description, :worms_density_id, user_ids: [],
      fluents_attributes: %i[id output_id ph color_id color_description odor_id odor_description cod ec bod tss tn tp sample_comments])
  end
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_form.html.erb
<%= form_with model: inspection, url:[@plant, inspection], local: true, builder: BFFormBuilder do |form| %>
  <% if inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
      <% inspection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2 class="cell_division"><%= t(:general_info, scope: :inspection) %></h2>

  <div class="field no-border">
    <%= form.label :on_site_client %>
    <%= form.collection_select(:on_site_client, @on_site_client, :second, :first, {prompt: t(:select_option, scope: :inspection)}, class:'describe')  %>
  </div>

  <div class="field description <%= 'show' if inspection.on_site_client %> no-border">
    <%= form.label :on_site_user_id %>
    <%= form.collection_select(:on_site_user_id, @company_users, :id, :full_name, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :report_technician_id %>
    <%= form.collection_select(:report_technician_id, @biofiltro_users, :id, :full_name, {prompt: t(:select_option, scope: :inspection)}) %>
  </div>

  <div class="field">
    <%= form.label :notify %>
    <ul>
    <%= form.collection_check_boxes(:user_ids, @company_users + @biofiltro_users, :id, :full_name, include_hidden: false) do |user| %>
      <li><%= user.check_box %> <%= user.label %></li>
    <% end %>
    </ul>
  </div>

  <div class="field no-border date">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <h2 class="cell_division"><%= t(:water_quality, scope: :inspection) %></h2>

  <%= form.fields_for :fluents, @fluents do |fluent| %>
    <% _fluent = fluent.object.output.name %>
    <h3><%= fluent.hidden_field :output_id, value: fluent.object.output.id %><%= t(_fluent.downcase, scope: :inspection) %></h3>

    <div class="field">
      <%= fluent.label t(:fluent_sampling, fluent: t(_fluent.downcase, scope: :inspection), scope: [:activerecord, :attributes, :inspection]) %>
      <%= fluent.bf_value_field :ph, 'pH' %>
    </div>

    <div class="field no-border">
      <%= fluent.label t(:sampling_color, fluent: t(_fluent.downcase, scope: :inspection), scope: [:activerecord, :attributes, :inspection]) %>
      <%= fluent.collection_select(:color_id, @colors, :first, :second, {prompt: t(:select_option, scope: :inspection)}, class: 'describe') %>
    </div>

    <div class="field description">
      <%= fluent.label t(:color_description, fluent: t(_fluent.downcase, scope: :inspection), scope: [:activerecord, :attributes, :inspection]) %>
      <%= fluent.text_area :color_description %>
    </div>

    <div class="field no-border">
      <%= fluent.label t(:sampling_odor, fluent: t(_fluent.downcase, scope: :inspection), scope: [:activerecord, :attributes, :inspection]) %>
      <%= fluent.collection_select(:odor_id, @odors, :first, :second, {prompt: t(:select_option, scope: :inspection)}, class:'describe')  %>
    </div>

    <div class="field description">
      <%= fluent.label t(:odor_description, fluent: t(_fluent.downcase, scope: :inspection), scope: [:activerecord, :attributes, :inspection]) %>
      <%= fluent.text_area :odor_description %>
    </div>

    <div class="field">
      <%= fluent.label :cod %>
      <%= fluent.bf_value_field :cod, 'mg/L' %>
    </div>

    <div class="field">
      <%= fluent.label :ec %>
      <%= fluent.bf_value_field :ec, 'µS/cm' %>
    </div>

    <div class="field">
      <%= fluent.label :bod %>
      <%= fluent.bf_value_field :bod, 'mg/L' %>
    </div>

    <div class="field">
      <%= fluent.label :tss %>
      <%= fluent.bf_value_field :tss, 'mg/L' %>
    </div>

    <div class="field">
      <%= fluent.label :tn %>
      <%= fluent.bf_value_field :tn, 'mg/L' %>
    </div>

    <div class="field">
      <%= fluent.label :tp %>
      <%= fluent.bf_value_field :tp, 'mg/L' %>
    </div>

    <div class="field">
      <%= fluent.label :sample_comments %>
      <%= fluent.text_area :sample_comments %>
    </div>
    <% end %>

  <h2 class="cell_division"><%= t(:primary_screen, scope: :inspection) %></h2>

  <div class="field no-border">
    <%= form.label :screen_id %>
    <%= form.collection_select(:screen_id, @screens, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :collection_bin_id %>
    <%= form.collection_select(:collection_bin_id, @collectionbins, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field">
    <%= form.label :screen_comments %>
    <%= form.text_area :screen_comments %>
  </div>

  <h2 class="cell_division"><%= t(:pumps_irrigation, scope: :inspection) %></h2>

  <div class="field no-border">
    <%= form.label :noise_id %>
    <%= form.collection_select(:noise_id, @noises, :first, :second, {prompt: t(:select_option, scope: :inspection)}, class:'describe') %>
  </div>

  <div class="field description">
    <%= form.label :pumps_noise_description %>
    <%= form.text_area :pumps_noise_description %>
  </div>

  <div class="field">
    <%= form.label :pumps_psi %>
    <%= form.bf_value_field :pumps_psi, 'PSI' %>
  </div>

  <div class="field no-border">
    <%= form.label :sprinklers_pressure_id %>
    <%= form.collection_select(:sprinklers_pressure_id, @sprinklers_pressures, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :sprinklers_head_id %>
    <%= form.collection_select(:sprinklers_head_id, @sprinklers_heads, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :piping_id %>
    <%= form.collection_select(:piping_id, @pipings, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field">
    <%= form.label :pumps_comments %>
    <%= form.text_area :pumps_comments %>
  </div>

  <h2 class="cell_division"><%= t(:bida, scope: :inspection) %></h2>

  <div class="field no-border">
    <%= form.label :system_surface_id %>
    <%= form.collection_select(:system_surface_id, @system_surfaces, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :worms_color_id %>
    <%= form.collection_select(:worms_color_id, @worms_color, :first, :second, {prompt: t(:select_option, scope: :inspection)}, class:'describe') %>
  </div>

  <div class="field description">
    <%= form.label :worms_color_description %>
    <%= form.text_area :worms_color_description %>
  </div>

  <div class="field no-border">
    <%= form.label :worms_activity_id %>
    <%= form.collection_select(:worms_activity_id, @worms_activity, :first, :second, {prompt: t(:select_option, scope: :inspection)}, class:'describe') %>
  </div>

  <div class="field description">
    <%= form.label :worms_activity_description %>
    <%= form.text_area :worms_activity_description %>
  </div>

  <div class="field no-border">
    <%= form.label :worms_density_id %>
    <%= form.collection_select(:worms_density_id, @worms_density, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :bed_compaction_id %>
    <%= form.collection_select(:bed_compaction_id, @bed_compactions, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :ponding_id %>
    <%= form.collection_select(:ponding_id, @pondings, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field">
    <%= form.label :bida_comments %>
    <%= form.text_area :bida_comments %>
  </div>

  <h2 class="cell_division"><%= t(:general, scope: :inspection) %></h2>

  <div class="field no-border">
    <%= form.label :odor_id %>
    <%= form.collection_select(:odor_id, @odors, :first, :second, {prompt: t(:select_option, scope: :inspection)}, class:'describe')  %>
  </div>

  <div class="field description">
    <%= form.label :plant_odor_description %>
    <%= form.text_area :plant_odor_description %>
  </div>

  <div class="field no-border">
    <%= form.label :birds %>
    <%= form.select(:birds, @birds, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <div class="field no-border">
    <%= form.label :fly_id %>
    <%= form.collection_select(:fly_id, @flies, :first, :second, {prompt: t(:select_option, scope: :inspection)})  %>
  </div>

  <h2 class="cell_division"><%= t(:summary, scope: :inspection) %></h2>

  <div class="field">
    <%= form.label :summary_comments %>
    <%= form.text_area :summary_comments %>
  </div>

  <div class="actions">
    <%= form.submit class: 'action-btn' %>
  </div>
<% end %>

app/views/inspections/index.html.erb
<% if can? :create, Inspection %>
  <%= render 'shared/buttons/option_button', alt: 'header' do %>
    <li class="option-button__option"><%= link_to t(:new, scope: :inspection), new_plant_inspection_path(@plant), class: 'option-button__option-link' %></li>
  <% end %>
<% end %>

<h2 class="main__title"><%= t(:index, scope: :inspection) %></h2>

<%= render 'shared/tables/elements_list', headers: [t(:number, scope: :inspection), t(:options, scope: :global)], title: t(:all, scope: :inspection) do %>
<% @inspections.each do |inspection| %>
  <tr class="table_main__table-row">
    <td class="table_main__table-data--left-text"><%= link_to "##{inspection.id} | #{inspection.date}", plant_inspection_path(@plant, inspection), class: 'table_main__link-show' %></td>
    <td class="table_main__table-data--options">
      <a href="#" class="table_main__link--options"></a>
      <div class="options_menu">
        <ul class="options_menu__list">
          <% if can? :read, Inspection %><li class="options_menu__item"><%= link_to t(:show, scope: :global), plant_inspection_path(@plant, inspection), class: 'options_menu__link' %></li><% end %>
          <% if can? :edit, Inspection %><li class="options_menu__item"><%= link_to t(:edit, scope: :global), edit_plant_inspection_path(@plant, inspection), class: 'options_menu__link' %></li><% end %>
          <% if can? :destroy, Inspection %><li class="options_menu__item"><%= link_to t(:destroy, scope: :global), plant_inspection_path(@plant, inspection), class: 'options_menu__link', method: :delete, data: { confirm: t(:confirm, scope: :global) } %></li><% end %>
        </ul>
        <div class="unclick"></div>
      </div>
  </tr>
<% end %>
<% end %>

app/views/inspections/new.html.erb
<h2 class="main__title"><%= t(:new, scope: :inspection) %></h2>

<%= render 'form', inspection: @inspection %>